import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from datetime import datetime
from database import(
    get_all_zones,
    get_all_reports,
    get_all_sos,
    get_recent_reports
)

#  Admin dashboard page.
#
# Shows a complete overview of campus safety:
#   - Live stats at the top
#   - AI safety summary
#   - SOS alerts table
#   - Incident reports by zone (bar chart)
#   - Severity distribution (pie chart)
#   - Recent reports feed
#   - Zone status table

# PAGE CONFIG
st.set_page_config(
    page_title = "Dashboard — CampusSafe",
    page_icon  = "📊",
    layout     = "wide"
)

# LOGIN GUARD
if not st.session_state.get("logged_in"):
    st.warning("Please login first.")
    st.stop()

user = st.session_state.user

# HEADER
st.title("📊 Safety Dashboard")
st.caption(
    f"DAVV Indore  ·  "
    f"Last refreshed: {datetime.now().strftime('%d %b %Y, %I:%M %p')}"
)
st.write("---")

# LOAD ALL DATA
zones          = get_all_zones()
all_reports    = get_all_reports()
recent_reports = get_recent_reports(days=7)
all_sos        = get_all_sos()

# Convert to DataFrames
reports_df = pd.DataFrame(all_reports) if all_reports else pd.DataFrame()
sos_df     = pd.DataFrame(all_sos)     if all_sos     else pd.DataFrame()
zones_df   = pd.DataFrame(zones)       if zones       else pd.DataFrame()

# ROW 1: LIVE STATS 
col1, col2, col3, col4, col5 = st.columns(5)

unsafe_count  = sum(1 for z in zones if z["safety_level"] == "unsafe")
caution_count = sum(1 for z in zones if z["safety_level"] == "caution")
safe_count    = sum(1 for z in zones if z["safety_level"] == "safe")
active_sos    = sum(1 for s in all_sos if s["status"] == "active")

col1.metric(
    label = "Total Reports",
    value = len(all_reports),
    delta = f"{len(recent_reports)} this week"
)
col2.metric(
    label = "Active SOS",
    value = active_sos,
    delta = f"{len(all_sos)} total"
)
col3.metric(
    label = "Unsafe Zones",
    value = unsafe_count,
    delta = f"of {len(zones)} total",
    delta_color = "inverse"
)
col4.metric(
    label = "Caution Zones",
    value = caution_count,
)
col5.metric(
    label = "Safe Zones",
    value = safe_count,
)

st.write("---")

# ── ROW 2: AI SAFETY SUMMARY
st.subheader("AI Safety Briefing")
st.caption("Generated by Ollama using live campus data")

if "ai_summary" not in st.session_state:
    st.session_state.ai_summary = None

col1, col2 = st.columns([3, 1])

with col2:
    if st.button(
        "Generate AI Briefing",
        use_container_width = True
    ):
        with st.spinner("Asking Ollama..."):
            try:
                from ai import get_safety_summary
                st.session_state.ai_summary = get_safety_summary()
            except Exception:
                st.session_state.ai_summary = (
                    "Ollama is not running. "
                    "Start it with: ollama serve"
                )

with col1:
    if st.session_state.ai_summary:
        st.info(f"🤖 {st.session_state.ai_summary}")
    else:
        st.caption(
            "Click 'Generate AI Briefing' to get an "
            "AI-written safety summary using live data."
        )

st.write("---")

# ROW 3: CHARTS
st.subheader("Incident Analytics")

if reports_df.empty:
    st.info("No reports yet. Add some data to see charts.")

else:
    chart_col1, chart_col2 = st.columns(2)

# Chart 1: Reports per Zone (Bar chart)
with chart_col1:
        st.write("**Reports by Location**")

        # Counts how many reports each zone has
        # value_counts() counts occurrences of each unique value
        location_counts = (
            reports_df["location_name"]
            .value_counts()
            .reset_index()
        )
        location_counts.columns = ["Location", "Reports"]

        fig_bar = px.bar(
            location_counts,
            x              = "Reports",
            y              = "Location",
            orientation    = "h",       # horizontal bars
            color          = "Reports",
            color_continuous_scale = ["green", "orange", "red"],
            text           = "Reports"  # show number on each bar
        )
        fig_bar.update_layout(
            height          = 350,
            showlegend      = False,
            margin          = dict(l=0, r=0, t=10, b=0),
            plot_bgcolor    = "rgba(0,0,0,0)",
            paper_bgcolor   = "rgba(0,0,0,0)",
            coloraxis_showscale = False
        )
        fig_bar.update_traces(
            textposition = "outside"
        )
        st.plotly_chart(fig_bar, use_container_width=True)

# Chart 2: Severity Distribution (Pie chart)
with chart_col2:
        st.write("**Severity Distribution**")

        severity_labels = {
            1: "1 - Minor",
            2: "2 - Low",
            3: "3 - Medium",
            4: "4 - High",
            5: "5 - Critical"
        }

        severity_counts = (
            reports_df["severity"]
            .value_counts()
            .reset_index()
        )
        severity_counts.columns = ["Severity", "Count"]
        severity_counts["Label"] = severity_counts["Severity"].map(
            severity_labels
        )

        fig_pie = px.pie(
            severity_counts,
            values = "Count",
            names  = "Label",
            color_discrete_sequence = [
                "#2ecc71",  # green  — minor
                "#f1c40f",  # yellow — low
                "#e67e22",  # orange — medium
                "#e74c3c",  # red    — high
                "#8e44ad"   # purple — critical
            ]
        )
        fig_pie.update_layout(
            height        = 350,
            margin        = dict(l=0, r=0, t=10, b=0),
            paper_bgcolor = "rgba(0,0,0,0)",
            legend        = dict(orientation="h", yanchor="bottom",
                                 y=-0.3, xanchor="center", x=0.5)
        )
        st.plotly_chart(fig_pie, use_container_width=True)

# ROW 4: ZONE STATUS
st.write("---")
st.subheader("Zone Safety Status")
st.caption("Updated automatically by AI after each new report")

if not zones_df.empty:

    # Color each row based on safety level
    # We show the table manually instead of using st.dataframe
    # so we can control the colors

    zone_col1, zone_col2, zone_col3 = st.columns(3)

    safe_zones    = [z for z in zones if z["safety_level"] == "safe"]
    caution_zones = [z for z in zones if z["safety_level"] == "caution"]
    unsafe_zones  = [z for z in zones if z["safety_level"] == "unsafe"]

    with zone_col1:
        st.success(f"**Safe ({len(safe_zones)})**")
        for z in safe_zones:
            ai_time = z.get("ai_updated_at", "default")
            if ai_time and ai_time != "default":
                ai_time = ai_time[:16]
            st.write(f"🟢 **{z['name']}**")
            st.caption(f"{z['description']}")

    with zone_col2:
        st.warning(f"**Caution ({len(caution_zones)})**")
        for z in caution_zones:
            st.write(f"🟡 **{z['name']}**")
            st.caption(f"{z['description']}")

    with zone_col3:
        st.error(f"**Unsafe ({len(unsafe_zones)})**")
        for z in unsafe_zones:
            st.write(f"🔴 **{z['name']}**")
            st.caption(f"{z['description']}")


# ── ROW 5: SOS ALERTS TABLE ───────────────────────────────────────────────────
st.write("---")
st.subheader("SOS Alert History")

if sos_df.empty:
    st.info("No SOS alerts yet.")

else:
    # Filter tabs
    sos_tab1, sos_tab2 = st.tabs([
        f"All Alerts ({len(all_sos)})",
        f"Active ({active_sos})"
    ])

    with sos_tab1:
        for alert in all_sos:

            status_icon = "🔴" if alert["status"] == "active" else "🟢"
            maps_link   = (
                f"https://maps.google.com/?"
                f"q={alert['latitude']},{alert['longitude']}"
            )

            with st.expander(
                f"{status_icon} Alert #{alert['id']}  —  "
                f"{alert['user_name']}  —  "
                f"{alert['triggered_at'][:16]}"
            ):
                col1, col2, col3 = st.columns(3)
                col1.write(f"**Student:** {alert['user_name']}")
                col2.write(f"**Status:** {alert['status'].capitalize()}")
                col3.write(f"**Time:** {alert['triggered_at'][11:16]}")
                st.markdown(f"[📍 Open on Google Maps]({maps_link})")

                # Admin can resolve active alerts from here
                if (alert["status"] == "active" and
                        user.get("role") == "admin"):
                    if st.button(
                        "Mark Resolved",
                        key=f"dash_resolve_{alert['id']}"
                    ):
                        from database import resolve_sos
                        resolve_sos(alert["id"])
                        st.success("Marked as resolved.")
                        st.rerun()

    with sos_tab2:
        active_alerts = [
            a for a in all_sos if a["status"] == "active"
        ]
        if not active_alerts:
            st.success("No active SOS alerts right now.")
        else:
            for alert in active_alerts:
                st.error(
                    f"🚨 **{alert['user_name']}** — "
                    f"{alert['triggered_at'][:16]}"
                )
                maps_link = (
                    f"https://maps.google.com/?"
                    f"q={alert['latitude']},{alert['longitude']}"
                )
                st.markdown(f"[📍 Open Location]({maps_link})")
                st.write("---")


# ROW 6: RECENT REPORTS FEED 
st.write("---")
st.subheader("Recent Incident Reports")
st.caption("Latest 15 reports submitted by students")

severity_icon = {
    1: "🟢", 2: "🟡", 3: "🟠", 4: "🔴", 5: "🆘"
}

if not all_reports:
    st.info("No reports yet.")

else:
    for report in all_reports[:15]:
        icon = severity_icon.get(report["severity"], "⚪")

        with st.expander(
            f"{icon} {report['location_name']}  —  "
            f"{report['reported_at'][:16]}  —  "
            f"{report['user_name']}"
        ):
            st.write(f"**{report['description']}**")

            col1, col2 = st.columns(2)
            col1.caption(f"Severity: {report['severity']}/5")
            col2.caption(f"Time: {report['reported_at'][11:16]}")


# REFRESH BUTTON 
st.write("---")

col1, col2 = st.columns([4, 1])
with col2:
    if st.button("Refresh Dashboard", use_container_width=True):
        st.session_state.ai_summary = None
        st.rerun()